/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOCBSHAPE_MN
#define ROOCBSHAPE_MN

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooCBShape_MN : public RooAbsPdf {
public:
  RooCBShape_MN() {} ; 
  RooCBShape_MN(const char *name, const char *title,
	      RooAbsReal& _m,
	      RooAbsReal& _m0,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _n);
  RooCBShape_MN(const RooCBShape_MN& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooCBShape_MN(*this,newname); }
  inline virtual ~RooCBShape_MN() { }

protected:

  RooRealProxy m ;
  RooRealProxy m0 ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooCBShape_MN,1) // Your description goes here...
};
 
#endif
