/**
 * @Author: Billy Li <billyli>
 * @Date:   05-05-2022
 * @Email:  li000400@umn.edu
 * @Last modified by:   billyli
 * @Last modified time: 05-05-2022
 */



/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *****************************************************************************/

// Your description goes here...

#include "Riostream.h"

#include "RooExpmGauss.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
#include <math.h>
#include "TMath.h"

ClassImp(RooExpmGauss);

 RooExpmGauss::RooExpmGauss(const char *name, const char *title,
                        RooAbsReal& _x,
                        RooAbsReal& _mu,
                        RooAbsReal& _sigma,
                        RooAbsReal& _beta,
                        RooAbsReal& _m) :
   RooAbsPdf(name,title),
   x("x","x",this,_x),
   mu("mu","mu",this,_mu),
   sigma("sigma","sigma",this,_sigma),
   beta("beta","beta",this,_beta),
   m("m","m",this,_m)
 {
 }


 RooExpmGauss::RooExpmGauss(const RooExpmGauss& other, const char* name) :
   RooAbsPdf(other,name),
   x("x",this,other.x),
   mu("mu",this,other.mu),
   sigma("sigma",this,other.sigma),
   beta("beta",this,other.beta),
   m("m",this,other.m)
 {
 }



 Double_t RooExpmGauss::evaluate() const
 {
     Double_t t = (x-mu)/sigma;

     Double_t absBeta = fabs((Double_t)beta);

     if (t < -absBeta){
       Double_t m_inv = 1/m;
       Double_t A = exp(absBeta*absBeta*(m_inv-0.5));
       Double_t omega = m_inv*TMath::Power(absBeta, 2-m);
       Double_t abs_t = fabs(t);
       return A*exp(-omega*TMath::Power(abs_t,m));

     } else {
       return exp(-0.5*t*t);
     }
 }
