/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXPPOLY2
#define ROOEXPPOLY2

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExpPoly2 : public RooAbsPdf {
public:
  RooExpPoly2() {} ; 
  RooExpPoly2(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _a,
	      RooAbsReal& _b);
  RooExpPoly2(const RooExpPoly2& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExpPoly2(*this,newname); }
  inline virtual ~RooExpPoly2() { }

protected:

  RooRealProxy x ;
  RooRealProxy a ;
  RooRealProxy b ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooExpPoly2,1) // Your description goes here...
};
 
#endif
