/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXPMGAUSS
#define ROOEXPMGAUSS

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExpmGauss : public RooAbsPdf {
public:
  RooExpmGauss() {} ; 
  RooExpmGauss(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _sigma,
	      RooAbsReal& _beta,
	      RooAbsReal& _m);
  RooExpmGauss(const RooExpmGauss& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExpmGauss(*this,newname); }
  inline virtual ~RooExpmGauss() { }

protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy sigma ;
  RooRealProxy beta ;
  RooRealProxy m ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooExpmGauss,1) // Your description goes here...
};
 
#endif
