/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
  * This code was autogenerated by RooClassFactory                            * 
 *****************************************************************************/

#ifndef ROOEXPCBSHAPE
#define ROOEXPCBSHAPE

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"
 
class RooExpCBShape : public RooAbsPdf {
public:
  RooExpCBShape() {} ; 
  RooExpCBShape(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _sigma,
	      RooAbsReal& _alpha,
	      RooAbsReal& _n,
	      RooAbsReal& _beta);
  RooExpCBShape(const RooExpCBShape& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooExpCBShape(*this,newname); }
  inline virtual ~RooExpCBShape() { }

protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy sigma ;
  RooRealProxy alpha ;
  RooRealProxy n ;
  RooRealProxy beta ;
  
  Double_t evaluate() const ;

private:

  ClassDef(RooExpCBShape,1) // Your description goes here...
};
 
#endif
